### ISSUE TITLE
YouTube Vanced

### ISSUE THREAD

**Issue by syauqishamsuri** [xeon1989/Proton-X50-APK-Installer#12]
Hi bro, good day to you. i try to download YouTube using the youtube vanced link you provided (**https://youtubevanced.com/**) but seems like it doesn't working well. may i know is v2.6.2 is the right version or should i try the older version?

**Comment by xeon1989** [comment]
As I am not able to try for you, anyone that tried that version please feedback in tis issue.

**Comment by apache289** [comment]
> Hi bro, good day to you. i try to download YouTube using the youtube vanced link you provided (**https://youtubevanced.com/**) but seems like it doesn't working well. may i know is v2.6.2 is the right version or should i try the older version?

I was using this version from here : https://apkmodhere.com/youtube-vanced/com.vanced.android.youtube
but 404 now :(

**Comment by amiraizat124** [comment]
Can download vanced from here

https://github.com/Norikiru/VancedAPKs/tags

**Comment by amiraizat124** [comment]
> Hi bro, good day to you. i try to download YouTube using the youtube vanced link you provided (**https://youtubevanced.com/**) but seems like it doesn't working well. may i know is v2.6.2 is the right version or should i try the older version?

This is vanced manager, not youtube vanced
