### ISSUE TITLE
geely haoyue/okavango

### ISSUE THREAD

**Issue by jett111** [xeon1989/Proton-X50-APK-Installer#15]
nothings happen when I plug the flash drive(FAT32) in USB port. Look at the attached file below
![1](https://user-images.githubusercontent.com/82150456/187053782-86520827-46c7-424f-8e0a-d9beed2423e3.jpg)
![2](https://user-images.githubusercontent.com/82150456/187053783-fc50c4f7-c827-4c0b-9a77-f6761e97ce92.jpeg)

**Comment by jett111** [comment]
![1](https://user-images.githubusercontent.com/82150456/187053794-56579e8a-b0c6-407d-beec-feaa7142ee72.jpg)

**Comment by jett111** [comment]
![1](https://user-images.githubusercontent.com/82150456/187053806-2272c25e-b704-4bc3-b562-aa17de165b16.jpeg)

**Comment by xeon1989** [comment]
Hi, this is the script for GKUI based Proton X50.
Despite Okavango runs Android 5.1, this script didn't meant to compatible with other model of Geely's car.

**Comment by jett111** [comment]
Its working but How do I connect to the internet connection? Also when I open waze it prompted no GPS connection
