### ISSUE TITLE
No GPS connection waze

### ISSUE THREAD

**Issue by jett111** [xeon1989/Proton-X50-APK-Installer#16]
When I open the app it says no GPS connection and I dont know how to connect in wifi

**Comment by xeon1989** [comment]
Hi, i think you need to enable wifi with apps such as Wifi Manager.
Perhaps you may the GPS once Wifi enabled.
Else, try other Waze version.

**Comment by jett111** [comment]
So i need to install wifi manager?

**Comment by jett111** [comment]
Netflix and maps also not working since im not connected to wifi. I tried net manager to connect to internet but still the app not working

**Comment by jett111** [comment]
is it safe to root the head unit?

**Comment by xeon1989** [comment]
Hi, as I mention earlier, I am not able to comment because the Malaysian variant are not the same as Geely Coolray in Philippine.
Please explore yourself or ask for help in your local community.
