### ISSUE TITLE
Apkpure app stuck after uninstall 

### ISSUE THREAD

**Issue by davidkon** [xeon1989/Proton-X50-APK-Installer#21]
Hi
First of all, thank you for your effort! 

I ran the install script and the Apkpure app was installed in the android.

I wanted to uninstall it, so I performed a system reset. All the other apps were removed but Apkpure remains. 

I ran the uninstall script but it did not run. 

I installed ES explorer and removed Apkpure.
After a reboot, Apkpure came back.

Is there a way of getting rid of it?

**Comment by xeon1989** [comment]
> remains

Hi, how do you install apkpure? By copying it to /data/app/ES/ or install via ES File explorer?

**Comment by davidkon** [comment]
I did not install it manually, it just appeared after running the install script. Super weird.

**Comment by xeon1989** [comment]
Hi, I believe you mistakenly place installation package of apkpure in /data/app/ES/.
Please try to run [Uninstallation script](https://github.com/xeon1989/Proton-X50-APK-Installer/blob/main/Uninstallation%20script/done.sh) to clear up and folder.
