### ISSUE TITLE
Head Unit got stuck to Emergency Call Center Screen

### ISSUE THREAD

**Issue by Apndj014** [xeon1989/Proton-X50-APK-Installer#22]
How to fix please. After installation everything was working fine but when i turn on the car the next day screen got stuck to "Emergency call center" I am unable access settings and what not. It's just stuck on that screen. Tried restarting the HU but to no avail

**Comment by xeon1989** [comment]
Hi, what's the version of your GKUI? Does the error message look like [this](https://m.facebook.com/groups/px50cm/permalink/1878633295824382/?mibextid=Nif5oz) ?
Please show the screen and upload here - if possible.

**Comment by xeon1989** [comment]
Hi, how's the status of you HU? Please let me know if you got out of "Emergency call center" screen or you may capture and upload the screen.

**Comment by Apndj014** [comment]
Hi sorry for the late response. I dont really know what happened but my HU is all good again after a day.
