### ISSUE TITLE
Any idea why it is not working on my Geely Coolray (PH)?

### ISSUE THREAD

**Issue by Krowberr** [xeon1989/Proton-X50-APK-Installer#24]
Hi, thanks so much for this!

I have minor concerns with the script. As far as I know, it seems that Proton x50 is the same as Geely Coolray in the Philippines, just their brand and model are different names. Not sure why it is not working on my end.

Is it might be because of the firmware/hardware issues? I can't tell to be honest. Any help would be much appreciated and hey, thanks really for this!

-Keith

**Comment by xeon1989** [comment]
Hi Keith,

I supposed Geely Coolray's HU in PH is running on Android KitKat while Proton X50 HU running on Android Lollipop. 
Therefore the X50 script won't works in Coolray and vise versa. 

-xeon

**Comment by Krowberr** [comment]
Hi Xeon, 

Oh, that clarifies it. No worries. Thanks so much!
