### ISSUE TITLE
Anyway to change the default ES File Explorer to other files explorer?

### ISSUE THREAD

**Issue by AceZero925** [xeon1989/Proton-X50-APK-Installer#38]
Bro, Any help on this? as i found that ES File Explorer feels laggy. I have tried to uninstall it but it auto reinstall back every time i start my car.

**Comment by AceZero925** [comment]
FYI I'm using your old script to do the installation. Not your newest script.

**Comment by xeon1989** [comment]
Please uninstall with uninstall script rather than from Settings app.
To replace file explorer, not all file explorer are supported.
I tried X-plore and it worked.
You just need to replace es.apk in usb before installation.

**Comment by AceZero925** [comment]
I'm planing on using Solid Explorer for the replacement. Will try to uninstall with your old uninstall script and install back using your new script. Anyway I found out that the new script are different from the old one I have. any differences?

**Comment by xeon1989** [comment]
Yes. 
Previous script copies .apk file into /data/app, thus the file explorer installed as system app. 
System app can't be uninstalled by standard method (thus your question 😉 ).
Latest script install ES.apk as user app, so you may uninstall file explorer within IHU like other app. 
See done.sh for more details. 

In case you can't find uninstaller in README.md, kindly download it [here](https://github.com/xeon1989/Proton-X50-APK-Installer-GKUI/releases/tag/v0.5a).

**Comment by AceZero925** [comment]
I have tried and it works. Thanks Mate 😉
