### ISSUE TITLE
Apply car play unable to full screen 

### ISSUE THREAD

**Issue by Hertz0706** [xeon1989/Proton-X50-APK-Installer#43]
recently after get back my car from proton(they did a hard reset i think on my car), i reinstall car link kit, and found out that my car play unable to full screen, every time dragged the notification bar down, or turned air con , the top panel will keep showing, is this a bug? anyone face before?

**Comment by xeon1989** [comment]
I bought CCPA for the test. For my case the notification bar is not shown until I disconnectCarlinkit app (floating button - Disconnect).
I tested with AA but not CP if that matters. 
Unfortunately I could not reproduce the issue.

**Comment by Hertz0706** [comment]
may i know which version of carlink apk you using ?

**Comment by xeon1989** [comment]
https://cn.carlinkit.com/autokit.html

I using version 2023.12.25 as of now since it's the first version with steering button control.
I have not tried latest version 2024.04.29.

**Comment by Satvingill** [comment]
Hi Chris ,
Can make a apk and post on your GitHub site of the new version when you are
free ?
Thanks

**Comment by Hertz0706** [comment]
> https://cn.carlinkit.com/autokit.html
> 
> I using version 2023.12.25 as of now since it's the first version with steering button control. I have not tried latest version 2024.04.29.

im using the 2024 version, still the same issue, everything was fine until i drag down the notification bar, or adjusted the aircon,  aircond interface popup, then the top notification area wont gone, i wonder why,

and may i know how to clear the carlinkit cache? i deleted it, but is seems the data still remained as i installed the new version of carlinkit i can direct connect with my phone without re-pair etc.

**Comment by Hertz0706** [comment]
hmm, the issue is solved, by turn off full screen in advance setting, which is very weird , another problem is i accidently turn on the assistive ball , even though i turn it off , when i start up car again it will appear again.
