### ISSUE TITLE
Ottocast P3 unable to connect android AUTO or Carlink kit

### ISSUE THREAD

**Issue by alvintay** [xeon1989/Proton-X50-APK-Installer#44]
Hi,
found i issue, Ottocast P3 unable to connect android AUTO or Carlink kit

**Comment by xeon1989** [comment]
Hi, so far only Carlinkit dongle are supported. If you want to use any Android box such as P3, you need CCPA / CCPW connected between IHU and Android box. 

IHU -- Carlinkit (CCPA/CCPW) -- your Ottocast P3
