### ISSUE TITLE
"APK" Problem parsing the package error

### ISSUE THREAD

**Issue by securez12345** [xeon1989/Proton-X50-APK-Installer#9]
Which version of
**Waze
Spotify
YouTube
Netflix**
you install?

I keep getting "Problem parsing the package error"

**Comment by xeon1989** [comment]
Hi, try this.

netflix v7.120.2 build 14 35591
spotify v8.7.32.1554
waze 4.80.0.1
youtube vanced v16.29.39

**Comment by securez12345** [comment]
THX, how about android auto or google map?
